Repository NeutonNakazonoJr/food-point, pull requests merged in 2024-04, with the labels that each got.

#4 Feature/router
  public/assets/styles/style.css
  public/index.html
  public/index.js
  public/js/components/header.js
  public/js/components/modalBuilder.js
  public/js/events/onStateChange.js
  public/js/index.js
  public/js/pages/landingPage.js
  public/js/router/router.js
  public/js/utils/htmlCreator.js
Labels: enhancement

#6 Enhancement/router
  public/index.html
  public/js/events/onStateChange.js
  public/js/index.js
  public/js/router/router.js
Labels: enhancement

#12 Enhancement/servering the website
  .gitignore
  public/assets/styles/homePage.css
  public/assets/styles/login.css
  public/js/components/loginPage.js
  public/js/index.js
  public/js/pages/homePage.js
  public/js/pages/landingPage.js
  public/js/router/router.js
  public/js/utils/cancelScroll.js
  src/app.js
  src/routes/pageRoutes.js
  src/routes/router.js
Labels: enhancement

#14 Feature/login endpoint
  .envExample
  README.md
  documentationApi.md
  package-lock.json
  package.json
  src/app.js
  src/controllers/loginController.js
  src/controllers/userController.js
  src/database/db-connection.js
  src/middlewares/loginMiddleware.js
  src/middlewares/userMiddleware.js
  src/repositories/userRepository.js
  src/routes/loginRoutes.js
  src/routes/router.js
  src/routes/userRoutes.js
  src/schemas/loginSchema.js
  src/schemas/userSchema.js
  src/utils/jwt.js
  src/utils/passwordEncryption.js
Labels: enhancement

#15 Feature/create new event
  public/assets/icons/Vector.svg
  public/assets/icons/arrow-rigth.svg
  public/assets/icons/calendar-red.svg
  public/assets/icons/cancel.svg
  public/assets/icons/clock.svg
  public/assets/icons/send-latter.svg
  public/assets/icons/text-icon.svg
  public/assets/styles/newEventBasic.css
  public/assets/styles/timeline.css
  public/index.html
  public/js/api/eventApi.js
  public/js/components/eventProgressBar.js
  public/js/components/header.js
  public/js/components/modalBuilder.js
  public/js/events/changeStageOfTimeline.js
  public/js/index.js
  public/js/pages/homePage.js
  public/js/pages/newEventBasic.js
  public/js/router/router.js
  public/js/utils/disableButton.js
  public/js/utils/stopScroll.js
  src/routes/pageRoutes.js
Labels: enhancement

#20 Feature/backend integration
  dump.sql
  package-lock.json
  package.json
  public/assets/styles/newEventBasic.css
  public/assets/styles/style.css
  public/assets/svg-backgrounds/doubt.svg
  public/index.html
  public/js/api/eventApi.js
  public/js/api/userApi.js
  public/js/components/header.js
  public/js/components/modalBuilder.js
  public/js/components/toast.js
  public/js/pages/RegisterPage.js
  public/js/pages/guestPage.js
  public/js/pages/homePage.js
  public/js/pages/loginPage.js
  public/js/pages/newEventBasic.js
  public/js/router/router.js
  src/app.js
  src/config/config.js
  src/controllers/loginController.js
  src/database/db-connection.js
  src/middlewares/loginMiddleware.js
  src/middlewares/userMiddleware.js
  src/routes/pageRoutes.js
  src/routes/pagesRoutes.js
  src/routes/privatePageRoutes.js
  src/routes/publicPageRoutes.js
  src/routes/router.js
Labels: enhancement

#21 hotfix: date and hours errors & css addNewEvent card
  public/assets/styles/homePage.css
  public/js/pages/homePage.js
  public/js/pages/newEventBasic.js
Labels: bug

#24 Feature/backend integration
  public/assets/icons/palet-collor-icon.svg
  public/assets/styles/homePage.css
  public/js/pages/homePage.js
  public/js/pages/newEventBasic.js
Labels: bug, enhancement

#26 Feature/guest end point
  dump.sql
  src/controllers/guestController.js
  src/middlewares/guestMiddleware.js
  src/middlewares/loginMiddleware.js
  src/repositories/guestRepository.js
  src/routes/guestRoutes.js
  src/routes/pagesRoutes.js
  src/routes/privatePageRoutes.js
  src/routes/publicPageRoutes.js
  src/routes/router.js
  src/schemas/guestSchema.js
Labels: enhancement

#29 Feature/menu page
  public/assets/icons/accompaniment-type-icon.svg
  public/assets/icons/appetizer-hover.svg
  public/assets/icons/appetizer.svg
  public/assets/icons/bandeja-de-comida 1.svg
  public/assets/icons/cupcake.svg
  public/assets/icons/dessert-type-icon.svg
  public/assets/icons/drink.svg
  public/assets/icons/enter-type-icon.svg
  public/assets/icons/guest-list-icon.svg
  public/assets/icons/home-icon.svg
  public/assets/icons/icecream.svg
  public/assets/icons/location-event-page-icon.svg
  public/assets/icons/location-event.svg
  public/assets/icons/main-type-icon.svg
  public/assets/icons/menu-icon.svg
  public/assets/icons/panquecas.svg
  public/assets/icons/pen.svg
  public/assets/icons/salad-hover.svg
  public/assets/icons/salad-type-icons.svg
  public/assets/icons/salad.svg
  public/assets/icons/salsicha.svg
  public/assets/styles/eventPage.css
  public/assets/styles/newEventMenu.css
  public/assets/styles/style.css
  public/index.html
  public/js/api/eventApi.js
  public/js/api/userApi.js
  public/js/events/onStateChange.js
  public/js/index.js
  public/js/pages/eventPage.js
  public/js/pages/menu/DishController.js
  public/js/pages/menu/components/aside.js
  public/js/pages/menu/components/display.js
  public/js/pages/menu/components/form.js
  public/js/pages/menu/menuPage.js
  public/js/router/router.js
  public/js/utils/htmlCreator.js
  src/app.js
  src/controllers/eventController.js
  src/controllers/ingredientController.js
  src/controllers/loginController.js
  src/controllers/userController.js
  src/middlewares/loginMiddleware.js
  src/middlewares/userMiddleware.js
  src/repositories/eventRepository.js
  src/repositories/ingredientRespository.js
  src/repositories/userRepository.js
  src/routes/eventRoutes.js
  src/routes/loginRoutes.js
  src/routes/pagesRoutes.js
  src/routes/router.js
  src/routes/userRoutes.js
Labels: enhancement

#32 Feature/menu page
  public/assets/styles/newEventMenu.css
  public/js/components/header.js
  public/js/pages/guestPage.js
  public/js/pages/menu/DishController.js
  public/js/pages/menu/components/display.js
  public/js/pages/menu/components/footer.js
  public/js/pages/menu/components/form.js
  public/js/pages/menu/menuPage.js
  public/js/pages/newEventBasic.js
Labels: enhancement
